rvm:
  - 2.1.0

before_install:
  - "gem install bundler -v '= 1.5.1'"

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role catarse SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database catarse_test;' -U catarse postgres"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake db:migrate"

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec"
    #- "bundle exec rake jasmine:ci" removed while jasmine has some bugs with ruby 2.1.0

branches:
  only:
    - master
