version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4-stretch-node-browsers
      - image: postgres:11.5
        environment:
          POSTGRES_DB: catarse_test
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: |
          sudo tee /etc/apt/sources.list.d/pgdg.list <<END 
            deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
          END
      - run: sudo wget https://www.postgresql.org/media/keys/ACCC4CF8.asc && sudo apt-key add ACCC4CF8.asc
      - run: sudo apt update
      - run: sudo apt install postgresql-client-11
      - run: bundle install
      - run: npm install
      - run: RAILS_ENV=test DATABASE_URL=postgres://postgres:example@localhost:5432/catarse_test bundle exec rake db:migrate
      - run: RAILS_ENV=test DATABASE_URL=postgres://postgres:example@localhost:5432/catarse_test bundle exec rspec spec

  deploy_sandbox:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - add_ssh_keys
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add git openssh
      - run: sh .circleci/deploy-sandbox.sh


workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      #- deploy_sandbox:
      #    requires:
      #      - build
      #    filters:
      #      branches:
      #        only: develop
